### ISSUE TITLE
Do you consider making it production ready ?

### ISSUE THREAD

**Issue by iamleson98** [ZeroX-DG/craftorio#1]
Hi bro @ZeroX-DG 
I did ran this project, Just a cube placed on a grid.
Do you consider making this production ready ? I'm not 3D professional but can contribute.
I'm curious about how minecraft can make infinite maps.

**Comment by ZeroX-DG** [comment]
Hey man, I forgot that I made this repo public lol.

This is just one of my experiment so I don't have any goal for it other than to test out Three.js haha. As you can see, the most cliche thing that people do when they learn Three.js is to create a Minecraft clone.

I'm not looking for any contribution on this repo yet, sorry. But feel free to fork it & start your own experiment if you're keen!

P/S: About Minecraft infinite maps thing, I have no idea how it work also haha. But I did found this cool video: https://youtu.be/CSa5O6knuwI
